name: Publish packages

on:
  push:
    branches: 
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm i -g @microsoft/rush
      - run: rush install
      - run: rush build
      - run: rush publish -p 
