name: Build and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - ready_for_review
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 6.10.0
    
    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: pnpm i -g @microsoft/rush -s
    - run: rush install
    - run: rush build
      env:
        CI: true
    - run: rush test
      env:
        CI: true
